Homework 26
RynkevichNikita/WD-12 pull request #4
Opened 2024-02-14 18:56 UTC by RynkevichNikita

2024-03-03 11:32 UTC, FilipovskyAlex requested changes

2024-03-03 11:32 UTC, FilipovskyAlex commented on app/Http/Requests/CustomerUpdateRequest.php
> +            'customerNumber' => ['exists:customers'],
вот тут нужно еще добавлять название колонки, потому что не будет работать. Или ты проверял и валидация работала?

2024-03-03 11:32 UTC, FilipovskyAlex commented on app/Http/Requests/CustomerUpdateRequest.php
> +    protected function failedValidation(Validator $validator)
нет смысла использовать этот метод, он по ум. будет возвращать 422 в случае ошибки валидации

2024-03-03 11:32 UTC, FilipovskyAlex commented on app/Http/Controllers/CustomerController.php
> +        $request->validated();
Когда мы используем свой класс реквеста, то нам нет смысла вызывать этот метод

2024-03-07 10:40 UTC, RynkevichNikita commented on app/Http/Requests/CustomerUpdateRequest.php
> +            'customerNumber' => ['exists:customers'],
Да, проверял. Все работает

Из документации:
> If the column option is not specified, the field name will be used.

2024-03-10 12:31 UTC, FilipovskyAlex approved these changes

2024-03-10 12:32 UTC, merged